# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Work/Vitis/ZynqTemplate/ZedBoard_VGA_IP/ZedBoard_OLED/ZedBoard_OLED.srcs/sources_1/new/charLib/charLib.xci
# IP: The module: 'charLib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Work/Vitis/ZynqTemplate/ZedBoard_VGA_IP/ZedBoard_OLED/OLED_HW.gen/sources_1/ip/charLib/charLib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'charLib'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Work/Vitis/ZynqTemplate/ZedBoard_VGA_IP/ZedBoard_OLED/ZedBoard_OLED.srcs/sources_1/new/charLib/charLib.xci
# IP: The module: 'charLib' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Work/Vitis/ZynqTemplate/ZedBoard_VGA_IP/ZedBoard_OLED/OLED_HW.gen/sources_1/ip/charLib/charLib_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'charLib'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
