/*
 * hid_touch.h
 *
 *  Created on: 1 Feb 2022
 *      Author: PeterB
 *
 *
 *
 *      Reverse engineering aided by RDD! HID Report Descriptor Decoder see Github https://github.com/abend0c1/hidrdd
 *
 *      Ultimately when the device is enumerated we should pull the values of ILI_MAX_X and ILI_MAX_Y from the device
 *      using the HID report data but I haven't had time to deal with this yet!
 *
 */

#ifndef SRC_HID_TOUCH_H_
#define SRC_HID_TOUCH_H_

#define ILITEK_VID			0x222A
#define ILITEK_TOUCH_PID	0x0001
#define NUM_TOUCH_POINTS	10		// 10 for the ILI2302 controller

/* 13.3" touch parameters */
#define ILI_MAX_X			16384
#define ILI_MAX_Y			9600
/* https://www.waveshare.com/product/displays/lcd-oled/lcd-oled-1/13.3inch-hdmi-lcd-h-with-case.htm */

/* 15.6" screen parameters */
//#define ILI_MAX_X			9600
//#define ILI_MAX_Y			9600
/* https://www.waveshare.com/product/displays/lcd-oled/lcd-oled-1/15.6inch-hdmi-lcd-h-with-case.htm */
/*
 * NOTE: for Waveshare screens VGA connection, this cable is also required:
 * https://www.waveshare.com/Mini-HDMI-Male-to-VGA-Female-Cable.htm
 *
 */

enum {

	HID_USAGE_DIGITISER_UNDEF			= 0x0000,
	HID_USAGE_DIGITISER 				= 0x0001,
	HID_USAGE_DIGITISER_PEN				= 0x0002,
	HID_USAGE_DIGITISER_LIGHT_PEN		= 0x0003,
	HID_USAGE_DIGITISER_TOUCH_SCREEN 	= 0x0004,
	HID_USAGE_DIGITISER_TOUCH_PAD		= 0x0005,
	HID_USAGE_DIGITISER_WHITEBOARD		= 0x0006
};

typedef struct TU_ATTR_PACKED {

	uint8_t  TouchID : 6; 			// Usage 0x000D0051: Contact Identifier, Value = 0 to 63
	uint8_t  TipSwitch : 1;       	// Usage 0x000D0042: Tip Switch, Value = 0 to 1
	uint8_t  : 1;                   // Pad
	uint16_t TouchX;                // Usage 0x00010030: X, Value = 0 to 16384
	uint16_t TouchY;                // Usage 0x00010031: Y, Value = 0 to 9600

} touch_point_t;

// Report Generated by ILI2302 touch screen decoder as reverse engineered by PJB
typedef struct TU_ATTR_PACKED {

	uint8_t  reportId;                       	// Report ID = 0x04 (4)
	// Collection: CA:TouchScreen CL:Finger
	touch_point_t points[NUM_TOUCH_POINTS]; 	// Details of current touch points
	// Collection: CA:TouchScreen
	uint32_t RelativeScanTime;          	// Usage 0x000D0056: Relative Scan Time, Value = 0 to 2147483647
	uint8_t  ContactCount;              	// Usage 0x000D0054: Contact Count, Value = 0 to 127
	uint8_t  pad_0[8];                  	// Pad

} hid_ilitek2302_t;



#endif /* SRC_HID_TOUCH_H_ */
