/*
 * our_time.c
 *
 *  Created on: 23 Apr 2019
 *      Author: peterb
 */

#include "pjbes_time.h"

extern config_datp_t	conf_p;

time_t get_zone_time( int z_idx, char* t_buf ) {

	time_t		t;

	/* Update Time Display */
	time(&t);	  						// Get the system time (UTC).
	t += t_zones[z_idx].utc_offset;		// Adjust for selected time zone
	if( t_buf != NULL ) {
		ctime_r( &t, t_buf );			// Append time to our text buffer
		t_buf[strlen(t_buf)-1] = 0;  	// Remove the newline character returned by ctime_r() function
	}
	return t;
}

time_t FreeRTOS_time( time_t *pxTime ) {

	time_t		time_now;

	if( pxTime != NULL ) {
		time( pxTime );
		*pxTime += t_zones[conf_p->tz_idx].utc_offset;
		return( *pxTime );
	} else {
		time( &time_now );
		time_now += t_zones[conf_p->tz_idx].utc_offset;
		return( time_now );
	}
}

struct tz_data t_zones[] = {

	{ {"UTC"}, {"Coordinated Universal Time"}, 0 },
	{ {"A"}, {"Alpha Time Zone Military"}, 3600 },
	{ {"ACDT"}, {"Australian Central Daylight Time"}, 37800 },
	{ {"ACST"}, {"Australian Central Standard Time"}, 34200 },
	{ {"ACT"}, {"Acre Time - South America"}, -18000 },
	{ {"ACWST"}, {"Australian Central Western Standard Time"}, 31500 },
	{ {"ADT"}, {"Arabia Daylight Time"}, 14400 },
	{ {"AEDT"}, {"Australian Eastern Daylight Time"}, 39600 },
	{ {"AEST"}, {"Australian Eastern Standard Time"}, 36000 },
	{ {"AFT"}, {"Afghanistan Time Asia"}, 16200 },
	{ {"AKDT"}, {"Alaska Daylight Time"}, -28800 },
	{ {"AKST"}, {"Alaska Standard Time"}, -32400 },
	{ {"ALMT"}, {"Alma-Ata Time Asia"}, 21600 },
	{ {"AMST"}, {"Amazon Summer Time"}, -10800 },
	{ {"AMDT"}, {"Armenia Daylight Time"}, 18000 },
	{ {"AMT"}, {"Amazon Time"}, -14400 },
	{ {"AMT"}, {"Armenia Time"}, 14400 },
	{ {"ANAST"}, {"Anadyr Summer Time"}, 43200 },
	{ {"ANAT"}, {"Anadyr Time"}, 43200 },
	{ {"AoE"}, {"Anywhere on Earth"}, -43200 },
	{ {"AQTT"}, {"Aqtobe Time"}, 18000 },
	{ {"ART"}, {"Argentina Time"}, -10800 },
	{ {"AST"}, {"Arabia Standard Time"}, 10800 },
	{ {"AST"}, {"Tiempo Estandar del Atlantico (Spanish)"}, -14400 },
	{ {"AT"}, {"Atlantic Time"}, -14400 },
	{ {"AWDT"}, {"Australian Western Daylight Time"}, 32400 },
	{ {"AWST"}, {"Australian Western Standard Time"}, 28800 },
	{ {"AZOST"}, {"Azores Summer Time"}, 0 },
	{ {"AZOT"}, {"Azores Time"}, -3600 },
	{ {"AZST"}, {"Azerbaijan Summer Time"}, 18000 },
	{ {"AZT"}, {"Azerbaijan Time"}, 14400 },
	{ {"B"}, {"Bravo Time Zone Military"}, 7200 },
	{ {"BNT"}, {"Brunei Darussalam Time"}, 28800 },
	{ {"BOT"}, {"Bolivia Time"}, -14400 },
	{ {"BRST"}, {"Braslian Summer Time"}, -7200 },
	{ {"BRT"}, {"Braslian Time"}, -10800 },
	{ {"BST"}, {"Bangladesh Standard Time"}, 21600 },
	{ {"BST"}, {"Bougainville Standard Time"}, 39600 },
	{ {"BST"}, {"British Summer Time"}, 3600 },				// 38
	{ {"BTT"}, {"Bhutan Time"}, 21600 },
	{ {"C"}, {"Charlie Time Zone Military"}, 10800 },
	{ {"CAST"}, {"Casey Time"}, 28800 },
	{ {"CAT"}, {"Central Africa Time"}, 7200 },
	{ {"CCT"}, {"Cocos Islands Time"}, 23400 },
	{ {"CDT"}, {"Central Daylight Time"}, -18000 },
	{ {"CDT"}, {"Cuba Daylight Time"}, -14400 },
	{ {"CEST"}, {"Central European Summer Time"}, 7200 },
	{ {"CET"}, {"Central European Time"}, 3600 },
	{ {"CHADT"}, {"Chatham Island Daylight Time"}, 49500 },
	{ {"CHAST"}, {"Chatham Island Standard Time"}, 45900 },
	{ {"CHOST"}, {"Choibalsan Summer Time"}, 32400 },
	{ {"CHOT"}, {"Choibalsan Time"}, 28800 },
	{ {"CHUT"}, {"Chuuk Time"}, 36000 },
	{ {"CIDST"}, {"Cayman Islands Daylight Saving Time"}, -14400 },
	{ {"CIT"}, {"Cayman Islands Time"}, -18000 },
	{ {"CKT"}, {"Cook Island Time"}, -36000 },
	{ {"CLST"}, {"Chile Summer Time"}, -10800 },
	{ {"CLT"}, {"Chile Standard Time"}, -14400 },
	{ {"COT"}, {"Colombia Time South America"}, -18000 },
	{ {"CT"}, {"Central Standard Time"}, -21600 },
	{ {"CST"}, {"Tiempo Central Estandar (Spanish)"}, -21600 },
	{ {"CST"}, {"China Standard Time"}, 28800 },
	{ {"CST"}, {"Cuba Standard Time"}, -18000 },
	{ {"CVT"}, {"Cape Verde Time"}, -3600 },
	{ {"CXT"}, {"Christmas Island Time"}, 25200 },
	{ {"ChST"}, {"Chamorro Standard Time"}, 36000 },
	{ {"D"}, {"Delta Time Zone Military"}, 14400 },
	{ {"DAVT"}, {"Davis Time"}, 25200 },
	{ {"DDUT"}, {"Dumont-d'Urville Time"}, 36000 },
	{ {"E"}, {"Echo Time Zone Military"}, 18000 },
	{ {"EASST"}, {"Easter Island Summer Time"}, -18000 },
	{ {"EAST"}, {"Easter Island Standard Time"}, -21600 },
	{ {"EAT"}, {"Eastern Africa Time"}, 10800 },
	{ {"ECT"}, {"Ecuador Time South America"}, -18000 },
	{ {"EDT"}, {"Eastern Daylight Time"}, -14400 },
	{ {"EDT"}, {"Tiempo de verano del Este (Spanish)"}, -14400 },
	{ {"EEST"}, {"Eastern European Summer Time"}, -10800 },
	{ {"OESZ"}, {"Osteuropaische Sommerzeit (German)"}, 10800 },
	{ {"EET"}, {"Eastern European Time"}, 7200 },
	{ {"EFATE"}, {"Efate Time"}, 39600 },
	{ {"EGST"}, {"Eastern Greenland Summer Time"}, 0 },
	{ {"EGT"}, {"East Greenland Time"}, -3600 },
	{ {"ET"}, {"Eastern Standard Time"},  -18000 },
	{ {"EST"}, {"Eastern Standard Time"}, -18000 },
	{ {"ET"}, {"Tiempo del Este (Spanish)"}, -18000 },
	{ {"F"}, {"Foxtrot Time Zone Military"}, 21600 },
	{ {"FET"}, {"Further-Eastern European Time"}, 10800 },
	{ {"FJST"}, {"Fiji Summer Time"}, 46800 },
	{ {"FJT"}, {"Fiji Time Pacific"}, 43200 },
	{ {"FKST"}, {"Falkland Islands Summer Time"}, -10800 },
	{ {"FKT"}, {"Falkland Island Time"}, -14400 },
	{ {"FNT"}, {"Fernando de Noronha Time"}, -7200 },
	{ {"G"}, {"Golf Time Zone Military"}, 25200 },
	{ {"GALT"}, {"Galapagos Time"}, -21600 },
	{ {"GAMT"}, {"Gambier Time"}, -32400 },
	{ {"GET"}, {"Georgia Standard Time"}, 14400 },
	{ {"GFT"}, {"French Guiana Time"}, -10800 },
	{ {"GILT"}, {"Gilbert Island Time"}, 43200 },
	{ {"GMT"}, {"Greenwich Mean Time"}, 0  }, 				// 107
	{ {"GST"}, {"Gulf Standard Time"}, 14400 },
	{ {"GST"}, {"Guam Standard Time"}, 36000 },
	{ {"GST"}, {"South Georgia Time"}, -7200 },
	{ {"GYT"}, {"Guyana Time"}, -14400 },
	{ {"H"}, {"Hotel Time Zone Military"}, 28800 },
	{ {"HAA"}, {"Heure Avance de l'Atlantique (French)"}, -10800 },
	{ {"HAC"}, {"Heure Avance du Centre (French)"}, -18000 },
	{ {"HAE"}, {"Heure Avance de l'Est (French)"}, -14400 },
	{ {"HAP"}, {"Heure Avance du Pacifique (French)"}, -25200 },
	{ {"HAR"}, {"Heure Avance des Rocheuses (French)"}, -21600 },
	{ {"HAT"}, {"Heure Avance de Terre-Neuve (French)"}, -9000 },
	{ {"HDT"}, {"Hawaii-Aleutian Daylight Time"}, -32400 },
	{ {"HKT"}, {"Hong Kong Time"}, 28800 },
	{ {"HLV"}, {"Hora Legal de Venezuela (Spanish)"}, -14400 },
	{ {"HNA"}, {"Heure Normale de l'Atlantique (French)"}, -14400 },
	{ {"HNC"}, {"Heure Normale du Centre (French)"}, -21600 },
	{ {"HNE"}, {"Heure Normale de l'Est (French)"}, -18000 },
	{ {"HNP"}, {"Heure Normale du Pacifique (French)"}, -28800 },
	{ {"HNR"}, {"Heure Normale des Rocheuses (French)"}, -25200 },
	{ {"HNT"}, {"Heure Normale de Terre-Neuve (French)"}, -12600 },
	{ {"HOVST"}, {"Hovd Summer Time"}, 28800 },
	{ {"HOVT"}, {"Hovd Time"}, 25200 },
	{ {"HST"}, {"Hawaii Standard Time"}, -36000 },
	{ {"I"}, {"India Time Zone Military"}, 32400 },
	{ {"ICT"}, {"Indochina Time"}, 25200 },
	{ {"IDT"}, {"Israel Daylight Time"}, 10800 },
	{ {"IOT"}, {"Indian Chagos Time"}, 21600 },
	{ {"IRST"}, {"Iran Summer Time"}, 16200 },
	{ {"IRKST"}, {"Irkutsk Summer Time"}, 32400 },
	{ {"IRKT"}, {"Irkutsk Time Asia"}, 28800 },
	{ {"IT"}, {"Iran Time Asia"}, 12600 },
	{ {"IST"}, {"India Standard Time"}, 19800 },
	{ {"IST"}, {"Irish Standard Time"}, 0 },
	{ {"IST"}, {"Irish Summer Time"}, 3600 },
	{ {"IST"}, {"Israel Standard Time"}, 7200 },
	{ {"JST"}, {"Japan Standard Time"}, 32400 },
	{ {"K"}, {"Kilo Time Zone Military"}, 36000 },
	{ {"KGT"}, {"Kyrgyzstan Time"}, 21600 },
	{ {"KIT"}, {"Kerguelen (Islands) Time"}, 18000 },
	{ {"KOST"}, {"Kosrae Time"}, 39600 },
	{ {"KRAST"}, {"Krasnoyarsk Summer Time Asia"}, 28800 },
	{ {"KRAT"}, {"Krasnoyarsk Time Asia"}, 25200 },
	{ {"KST"}, {"Korea Standard Time"}, 32400 },
	{ {"KUYT"}, {"Kuybyshev Time"}, 14400 },
	{ {"L"}, {"Lima Time Zone Military"}, 39600 },
	{ {"LHDT"}, {"Lord Howe Daylight Time"}, 39600 },
	{ {"LHST"}, {"Lord Howe Standard Time"}, 37800 },
	{ {"LINT"}, {"Line Islands Time"}, 50400 },
	{ {"M"}, {"Mike Time Zone Military"}, 43200 },
	{ {"MAGST"}, {"Magadan Summer Time"}, 43200 },
	{ {"MAGT"}, {"Magadan Time"}, 39600 },
	{ {"MART"}, {"Marquesas Time"}, -34200 },
	{ {"MAWT"}, {"Mawson Time"}, 18000 },
	{ {"MDT"}, {"Mountain Daylight Time"}, -21600 },
	{ {"MESZ"}, {"Mitteleuropische Sommerzeit (German)"}, 7200 },
	{ {"MEZ"}, {"Mitteleuropische Zeit (German)"}, 3600 },
	{ {"MHT"}, {"Marshall Islands Time Pacific"}, 43200 },
	{ {"MMT"}, {"Myanmar Time"}, 23400 },
	{ {"MSD"}, {"Moscow Daylight Time"}, 14400 },
	{ {"MSK"}, {"Moscow Standard Time"}, 10800 },
	{ {"MST"}, {"Mountain Standard Time"}, -25200 },
	{ {"MUT"}, {"Mauritius Time"}, 14400 },
	{ {"MVT"}, {"Maldives Time"}, 18000 },
	{ {"MYT"}, {"Malaysia Time"}, 28800 },
	{ {"N"}, {"November Time Zone Military"}, -3600 },
	{ {"NCT"}, {"New Caledonia Time"}, 39600 },
	{ {"NDT"}, {"Newfoundland Daylight Time"}, -9000  },
	{ {"NFT"}, {"Norfolk Time"}, 39600 },
	{ {"NOVST"}, {"Novosibirsk Summer Time"}, 25200 },
	{ {"NOVT"}, {"Novosibirsk Time"}, 21600 },
	{ {"NPT"}, {"Nepal Time"}, 20700 },
	{ {"NRT"}, {"Nauru Time"}, 43200 },
	{ {"NST"}, {"Newfoundland Standard Time"}, -12600 },
	{ {"NUT"}, {"Niue Time Pacific"}, -39600 },
	{ {"NZDT"}, {"New Zealand Daylight Time"}, 46800 },
	{ {"NZST"}, {"New Zealand Standard Time"}, 43200 },
	{ {"O"}, {"Oscar Time Zone Military"}, -7200 },
	{ {"OEZ"}, {"Osteuropaische Zeit (German)"}, 7200 },
	{ {"OMSST"}, {"Omsk Summer Time"}, 25200 },
	{ {"OMST"}, {"Omsk Standard Time"}, 21600 },
	{ {"ORAT"}, {"Oral Time"}, 18000 },
	{ {"P"}, {"Papa Time Zone Military"}, -10800 },
	{ {"PDT"}, {"Pacific Daylight Time"}, -25200 },
	{ {"PET"}, {"Peru Time"}, -18000 },
	{ {"PETST"}, {"Kamchatka Summer Time"}, 43200 },
	{ {"PETT"}, {"Petropavlovsk-Kamchatski Time"}, 43200 },
	{ {"PGT"}, {"Papua New Guinea Time"}, 36000 },
	{ {"PHOT"}, {"Phoenix Island Time"}, 46800 },
	{ {"PHT"}, {"Philippine Time"}, 28800 },
	{ {"PKT"}, {"Pakistan Standard Time"}, 	18000 },
	{ {"PMDT"}, {"Pierre & Miquelon Daylight Time"}, -7200 },
	{ {"PMST"}, {"Pierre & Miquelon Standard Time"}, -10800 },
	{ {"PONT"}, {"Pohnpei Standard Time"}, 39600 },
	{ {"PST"}, {"Pacific Standard Time"}, -28800 },
	{ {"PT"}, {"Tiempo del Pacifico (Spanish)"}, -28800 },
	{ {"PST"}, {"Pitcairn Standard Time"}, -28800 },
	{ {"PWT"}, {"Palau Time"}, 32400 },
	{ {"PYST"}, {"Paraguay Summer Time"}, -10800 },
	{ {"PYT"}, {"Paraguay Time"}, -14400 },
	{ {"PYST"}, {"Pyongyang Standard Time"}, 30600 },
	{ {"Q"}, {"Quebec Time Zone Military"}, -14400 },
	{ {"QYZT"}, {"Qyzylorda Time"}, 21600 },
	{ {"R"}, {"Romeo Time Zone Military"}, -18000 },
	{ {"RET"}, {"Reunion Time Africa"}, 14400 },
	{ {"ROTT"}, {"Rothera Time"}, -10800 },
	{ {"S"}, {"Sierra Time Zone Military"}, -21600 },
	{ {"SAKT"}, {"Sakhalin Time"}, 39600 },
	{ {"SAMT"}, {"Samara Time"}, 14400 },
	{ {"SAMST"}, {"Samara Summer Time"}, 14400 },
	{ {"SAST"}, {"South Africa Standard Time"}, 7200 },
	{ {"SBT"}, {"Solomon Islands Time"}, 39600 },
	{ {"SCT"}, {"Seychelles Time"}, 14400 },
	{ {"SGT"}, {"Singapore Time"}, 28800 },
	{ {"SRET"}, {"Srednekolymsk Time"}, 39600 },
	{ {"SRT"}, {"Suriname Time"}, -10800 },
	{ {"SST"}, {"Samoa Standard Time"}, -39600 },
	{ {"SYOT"}, {"Syowa Time"}, 10800 },
	{ {"T"}, {"Tango Time Zone Military"}, -25200 },
	{ {"TAHT"}, {"Tahiti Time"}, -36000 },
	{ {"TFT"}, {"French Southern and Antarctic Time"}, 18000 },
	{ {"TJT"}, {"Tajikistan Time"}, 18000 },
	{ {"TKT"}, {"Tokelau Time"}, 46800 },
	{ {"TLT"}, {"East Timor Time"}, 32400 },
	{ {"TMT"}, {"Turkmenistan Time"}, 18000 },
	{ {"TOST"}, {"Tonga Summer Time"}, 50400 },
	{ {"TOT"}, {"Tonga Time"}, 46800 },
	{ {"TRT"}, {"Turkey Time"}, 10800 },
	{ {"TVT"}, {"Tuvalu Time"}, 43200 },
	{ {"U"}, {"Uniform Time Zone Military"}, -28800 },
	{ {"ULAST"}, {"Ulaanbaatar Summer Time"}, 32400 },
	{ {"ULAT"}, {"Ulaanbaatar Time"}, 28800 },
	{ {"UYST"}, {"Uruguay Summer Time"}, -7200 },
	{ {"UYT"}, {"Uruguay Time"}, -10800 },
	{ {"UZT"}, {"Uzbekistan Time"}, 18000 },
	{ {"V"}, {"Victor Time Zone Military"}, -32400 },
	{ {"VET"}, {"Venezuelan Standard Time"}, -14400 },
	{ {"VLAST"}, {"Vladivostok Summer Time"}, 39600 },
	{ {"VLAT"}, {"Vladivostok Time"}, 36000 },
	{ {"VOST"}, {"Vostok Time"}, 21600 },
	{ {"VUT"}, {"Vanuatu Time"},  39600 },
	{ {"W"}, {"Whiskey Time Zone Military"}, -36000 },
	{ {"WAKT"}, {"Wake Time"}, 43200 },
	{ {"WARST"}, {"Western Argentine Summer Time"}, -10800 },
	{ {"WAST"}, {"West Africa Summer Time"}, 7200 },
	{ {"WAT"}, {"West Africa Time"}, 3600 },
	{ {"WEST"}, {"Western European Summer Time"}, 3600 },
	{ {"WESZ"}, {"Westeuropaische Sommerzeit (German)"}, 3600 },
	{ {"WET"}, {"Western European Time"}, 0 },
	{ {"WEZ"}, {"Westeuropaische Zeit (German)"}, 0 },
	{ {"WFT"}, {"Wallis and Futuna Time"}, 43200 },
	{ {"WGST"}, {"Western Greenland Summer Time"}, -7200 },
	{ {"WGT"}, {"West Greenland Time"}, -10800 },
	{ {"WIB"}, {"Western Indonesian Time"}, 25200 },
	{ {"WIT"}, {"Eastern Indonesian Time"}, 32400 },
	{ {"WITA"}, {"Central Indonesian Time"}, 28800 },
	{ {"WST"}, {"West Samoa Time"}, 46800 },
	{ {"WST"}, {"Western Sahara Summer Time"}, 3600 },
	{ {"WT"}, {"Western Sahara Standard Time"}, 0 },
	{ {"X"}, {"X-ray Time Zone Military"}, -39600 },
	{ {"Y"}, {"Yankee Time Zone Military"}, -43200 },
	{ {"YAKST"}, {"Yakutsk Summer Time Asia"}, 36000 },
	{ {"YAKT"}, {"Yakutsk Time Asia"}, 32400 },
	{ {"YAPT"}, {"Yap Time Pacific"}, 36000 },
	{ {"YEKST"}, {"Yekaterinburg Summer Time"}, 21600 },
	{ {"YEKT"}, {"Yekaterinburg Time"}, 18000 },
	{ {"Z"}, {"Zulu Time Zone Military"}, 0 },
	{ {"END"}, {"END"}, 0 }	// Terminating Entry - Do not remove!
};
